# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdiff" do
  version "0.0.3"

  on_macos do
    on_arm do
      sha256 "fcc453ba8930b40ce02ce772a80c97c20df96aa1c88d872d76c711440dbf1dd4"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a258265c30637409c368124541d190cf0b7c250214dd0e10f79023c28bbaee85"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f8ed7a3d5ede7575dd91d98d3668e9feeffcc807477b54b8d49f911e5ea927cc"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "024cfb1ade4385e55d57b0e663536c04d2e4dcab131c236a883cbea041315018"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdiff"
  desc "Browse a git repository's changes in the terminal"
  homepage "https://github.com/JNSAPH/gdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdiff"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdiff"]
    end
  end

  # No zap stanza required
end
