# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdiff" do
  version "0.0.1"

  on_macos do
    on_arm do
      sha256 "8d956d52865d9270faab11459a7d2e974f865637fe507169704766cc34781d48"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4057633263c970e5132fdc00eb50c227135d9f88253f177d3ea545c26c60a1da"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "29c95360db118c61ac3fd4a744f01478a2e61932764c100a4229162049f91d3e"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "744804ae9411e32ce968b1ae9315022d1fc6bee72b380d6321de7db7289b417a"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdiff"
  desc "Browse a git repository's changes in the terminal"
  homepage "https://github.com/JNSAPH/gdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdiff"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdiff"]
    end
  end

  # No zap stanza required
end
