# This file was generated by GoReleaser. DO NOT EDIT.
cask "gdiff" do
  version "0.0.2"

  on_macos do
    on_arm do
      sha256 "f393282b287c5d9805cb7b635410c1879535882e61b1e082a8e9ff31ce62cd8d"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58dced6b01416d22250d7eb5a6c458ebbd386fca647711fbccd38385c56151d8"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5832d9b782e4e1c0d183f788e500dcb0ca888043a9db8a5d30b02a728d1f334"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "479ff420d41b402d50ebd91b46f095cfc13836243c489f50f5d0dc8dde76bee2"
      url "https://github.com/JNSAPH/gdiff/releases/download/v#{version}/gdiff_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gdiff"
  desc "Browse a git repository's changes in the terminal"
  homepage "https://github.com/JNSAPH/gdiff"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gdiff"

  postflight do
    if OS.mac? && system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gdiff"]
    end
  end

  # No zap stanza required
end
